# Generated by Django 5.2.5 on 2025-08-14 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('borrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowreturn',
            name='borrowrecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowrecord', to='borrow.borrow'),
        ),
        migrations.AddField(
            model_name='return',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_books', to='books.book'),
        ),
        migrations.AddField(
            model_name='return',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowreturn',
            name='returnrecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnrecord', to='borrow.return'),
        ),
    ]
