# Generated by Django 5.2.5 on 2025-08-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowReturn',
        ),
    ]
